# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8e9fb2e0607e441589742a5c1d01ad4c13bc36a0123de186882ddce86b6eb189554ef42373006e308f37f5088f0dc90602d4c4619c62548b7d8ccfc0f16d015

test:
  secret_key_base: 8366f78bb73df70231868d5f3fd6b6debbcf4c3baa8a2d857e0785e902d16c86db27bbb143bd0293a80c2774241c4ba16e751edab80b8b4f88d70d6c530d645a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
